global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.163.com:465'
  smtp_from: MAIL_USERNAME
  smtp_auth_username: MAIL_USERNAME
  smtp_auth_password: MAIL_PASSWORD
  smtp_require_tls: false

route:
  group_by: ['alertname', 'instance', 'severity']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 15m
  receiver: 'mail'

receivers:
  - name: 'mail'
    email_configs:
      - to: MAIL_USERNAME
