version: '3.8'

networks:
  backend-network:
    external: true

services:
  mysqld-exporter:
    image: prom/mysqld-exporter
    volumes:
      - ./mysql/my.cnf:/.my.cnf
    networks:
      - backend-network
    ports:
      - "9104:9104"
    depends_on:
      mysql_service:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - backend-network
    depends_on:
      - mysqld-exporter

  grafana:
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PWD}
      GF_SECURITY_DISABLE_INITIAL_ADMIN_PASSWORD_HINT: "true"

      # 邮件通知核心
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: ${MAIL_SERVER}:${MAIL_PORT}
      GF_SMTP_USER: ${MAIL_USER}
      GF_SMTP_PASSWORD: ${MAIL_PASSWORD}
      GF_SMTP_FROM_ADDRESS: ${MAIL_USERNAME}
      GF_SMTP_FROM_NAME: "Grafana 监控报警"
      GF_SMTP_SSL_ENABLED: "false"
      GF_SMTP_STARTTLS_ENABLED: "false"
      GF_SMTP_SKIP_VERIFY: "true"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana    # 挂载本地配置文件并进行数据持久化到本地
    networks:
      - backend-network
    command: >
      sh -c "chown -R 472:472 /var/lib/grafana &&
            exec grafana-server --homepath=/usr/share/grafana"
    depends_on:
      - prometheus