networks:
  flask-backend-net:
    external: true

services:
  mysqld-exporter:
    image: prom/mysqld-exporter
    container_name: mysqld-exporter
    volumes:
      - ${PWD}/vendor/flask-monitoring-kit/mysql/my.cnf:/.my.cnf
    env_file:
      - ${PWD}/.env
    networks:
      - flask-net
    ports:
      - "9104:9104"
    depends_on:
      - mysql_service

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - flask-net
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'

  prometheus:
    image: prom/prometheus
    container_name: prometheus-service
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/vendor/flask-monitoring-kit/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PWD}/vendor/flask-monitoring-kit/prometheus/alert-rules.yml:/etc/prometheus/alert-rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - flask-net
    depends_on:
      - mysqld-exporter

  grafana:
    image: grafana/grafana
    container_name: grafana-service
    env_file:
      - ${PWD}/.env
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PWD}
      GF_SECURITY_DISABLE_INITIAL_ADMIN_PASSWORD_HINT: "true"
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/vendor/flask-monitoring-kit/grafana/provisioning:/etc/grafana/provisioning
      - ${PWD}/vendor/flask-monitoring-kit/grafana/dashboards:/var/lib/grafana/dashboards
      - ${PWD}/vendor/flask-monitoring-kit/grafana/config/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - flask-net
    depends_on:
      - prometheus
      - flask-backend
  
  alert-manager:
    image: prom/alertmanager:latest
    container_name: alert-manager
    env_file:
      - ${PWD}/.env
    ports:
      - "9093:9093"
    networks:
      - flask-net
    volumes:
      - ${PWD}/vendor/flask-monitoring-kit/alertmanager/entrypoint.sh:/start.sh
      - ${PWD}/vendor/flask-monitoring-kit/alertmanager/alert-manager.yml:/etc/alertmanager/alertmanager.yml
    entrypoint: ["/bin/sh", "/start.sh"]