groups:
- name: flask-alerts
  rules:
  - alert: HighErrorRate
    expr: rate(flask_http_errors_total[5m]) / rate(flask_http_requests_total[5m]) > 0.05
    for: 10m
    labels:
      severity: critical
    annotations:
      summary: "High error rate ({{ $value }}%)"

  - alert: MySQLDeadlock
    expr: rate(mysql_transaction_errors_total{error_type="deadlock"}[1h]) > 0
    labels:
      severity: warning
    annotations:
      description: "Deadlock detected in MySQL"