global:
  scrape_interval: 15s
  evaluation_interval: 60s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: 'flask'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['flask-backend:8088']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:\d+)?'
        replacement: '${1}'

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']
    metrics_path: '/metrics'