global:
  scrape_interval: 15s
  evaluation_interval: 60s

rule_files:
  - alert-rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alert-manager:9093

scrape_configs:
  - job_name: 'flask'
    static_configs:
      - targets: ['flask-backend:8088']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']
    metrics_path: '/metrics'
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: '/metrics'